### PR TITLE
feat: upgrade to the express@5.x (#691)

### PR DESCRIPTION
**Pull request by pnkp**
*Issue:* https://github.com/CodeGenieApp/serverless-express/issues/691 

*Description of changes:*

* upgraded to the express@5.x,
* adjusted the ServerlessRequest to the express@5.x implementation,
* ran: npm audit and npm audit fix,
* upgrade ejs to 3.1.10,
* added .idea folder to gitignore,
* removed unnecessary workflows for the node.js 14 and 16,
* updated the Node.js engine version to >= 18

# Checklist

- [x] Tests have been added and are passing
- [x] Documentation has been updated

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by brettstack** [comment]
Thanks for this! Is this backwards compatible? So you can use either express v4 or v5 with this change?

**Comment by pnkp** [comment]
> Thanks for this! Is this backwards compatible? So you can use either express v4 or v5 with this change?

I haven't checked, but I will

Edited:
It works for v4 and v5 express.

**Comment by pnkp** [comment]
@brettstack FYI. In terms of backwards compability, the express@5.x is compatible with the Node.js >= 18.

**Comment by pnkp** [comment]
@brettstack when will you release in the npm?

**Comment by brettstack** [comment]
It's out! Version 4.16.0. I've also updated https://codegenie.codes/ to use this latest version.

**Comment by pnkp** [comment]
I can't this version under the npm package: https://www.npmjs.com/package/@vendia/serverless-express?activeTab=versions
image

**Comment by brettstack** [comment]
This package is now published under https://www.npmjs.com/package/@codegenie/serverless-express/v/4.16.0

**Comment by pnkp** [comment]
> This package is now published under https://www.npmjs.com/package/@codegenie/serverless-express/v/4.16.0

Thank you!

**Pull request merged**
