### PR TITLE
Support Windows

### PR DESCRIPTION
**Pull request by MaksimAniskov**
Story: https://github.com/awslabs/aws-serverless-express/issues/38

### CODE REVIEW

**Comment by LuukMoret** [comment]
Can we please get this merged? This is the fix we need for the `ERROR: server error
{ Error: listen EACCES /tmp/server0.sock` error

**Comment by matttowerssonos** [comment]
+1 for merging this.

**Comment by John0x** [comment]
Please merge :)

**Comment by srfabio** [comment]
Yes please!

**Comment by mattmeye** [comment]
+1 please merge!

**Pull request merged**
