### PR TITLE
Adding support for gzip responses

### PR DESCRIPTION
**Pull request by lucianopf**
Trying to resolve the problem related at #45 I've found out that requests bigger than 1kb were being treated as gzipped.
So I added support to it in order to accept larger responses. =)

### CODE REVIEW

**Comment by brettstack** [comment]
Is there a reason we should be doing this in the library rather than doing it in your Express app? You could probably write some middleware to take care of this.

**Comment by lucianopf** [comment]
I faced this gzip behaviour using ClaudiaJS Api Builder, which has aws-serverless-express as a dependency.

This gzip behaviour seems to be a default nowadays, so everyone that starts and has a request a little bigger than the usual (such as a getAll method) will face this behaviour. (until it gets solved by the user a "problem").

I could just create a middleware as you told or create a PR at ClaudiaJS Api Builder but that would be a solution for a subgroup of aws-serverless-express users.

Instead I tried to solve the "problem" for everyone that use this lib, which is a superset..

- Require "zlib" ain't adding a dependency, so, it won't make the package bigger.
- I'm just "parsing" the response if the content-encoding is a gzip.

Doesn't seem to me to have a considerable side effect.

Can you please explain to me why would you think the better solution would be to implement this in every Express application as midlewares?

**Comment by brettstack** [comment]
Hi @lucianopf, what's the benefit of gzipping, and then unzipping? Why not just remove gzip from your application? We intend to support gzip in the future.

**Comment by lucianopf** [comment]
It seems to me that when you gzip some content you're transferring less bytes and by that lowering the latency of the responses.
It's an option, but since that's the default behavior it would be nice to be supported. 
This solution would only be used if the content-encoding is set as a gzip so it seems to me that this won't weight the users that choose to not to use gzip.

**Comment by brettstack** [comment]
> It seems to me that when you gzip some content you're transferring less bytes and by that lowering the latency of the responses.

But from what I can tell in this PR, you're unzipping a gzip before sending it down the wire. What's the benefit of that? Why not just not gzip in the first place?

> since that's the default behavior
Default behavior for what? In Express you need to explicitly do this, via the `compress` middleware or similar.

**Comment by lucianopf** [comment]
You are right mate!
Sorry I had my eyesight fixed in a point and that obfuscate the real goal! =D

Thanks @brettstack !

**Pull request closed without merging**
