### PR TITLE
Eventbridge events

### PR DESCRIPTION
**Pull request by cnuss**
*Description of changes:*

Similar to #468, adding support for EventBridge events

# Checklist

- [x] Tests have been added and are passing
- [x] Documentation has been updated

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by cnuss** [comment]
hey again @brett-vendia @brettstack ! 

adding another event source. comments greatly appreciated!

**Comment by cnuss** [comment]
hey! @brett-vendia @brettstack bubbling this to the top of your inbox. thoughts?

**Comment by MontoyaAndres** [comment]
Any update? Or is there a way to create a custom even bridge event for this? I just get this error all the time:
Screen Shot 2022-03-14 at 7 47 00 PM

**Comment by MontoyaAndres** [comment]
I tried this:

For the handler file, this is what I did:

```
require("source-map-support/register");
const serverlessExpress = require("@vendia/serverless-express");
const app = require("./src");
const {
  getRequestValuesFromEventBridge,
  emptyResponseMapper,
} = require("./src/lib/eventSource");

exports.handler = serverlessExpress({
  app,
  eventSource: {
    getRequest: getRequestValuesFromEventBridge,
    getResponse: emptyResponseMapper,
  },
});
```

This is the code for `src/lib/eventSource`:

```
const {
  emptyResponseMapper,
} = require("@vendia/serverless-express/src/event-sources/utils");

const getRequestValuesFromEventBridge = ({ event }) => {
  const method = "POST";
  const headers = { host: "events.amazonaws.com" };
  const body = event;

  return {
    method,
    headers,
    path: "/eventbridge",
    body,
  };
};

module.exports = {
  getRequestValuesFromEventBridge,
  emptyResponseMapper,
};
```

But It did not work... What can I do? :/

**Comment by H4ad** [comment]
@cnuss I created a refactored version of this library called [serverless-adapter](https://github.com/H4ad/serverless-adapter), still in beta but you can try to see if it works well, has event bridge support and many other event sources.

**Comment by brett-vendia** [comment]
Thanks @cnuss and apologies for this taking so long!

**Pull request merged**
