### PR TITLE
feat: add option of specifying resolveMode

### PR DESCRIPTION
**Pull request by brettstack**
Allows resolving using Promise, callback, or the default context.succeed.

API decisions were made to support backwards compatibility. We will clean up the interface in a future major version bump

```js
exports.handler = async (event, context) => awsServerlessExpress.proxy(server, event, context, 'PROMISE')
```

Please ensure all pull requests are made against the `develop` branch.

*Issue #134, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by brettstack** [comment]
Covered here https://github.com/awslabs/aws-serverless-express/pull/173/files#diff-971abd8c6c8db00bc212414ea19e1807R183

**Comment by keetonian** [comment]
Ok, thank you for the clarification!

**Comment by zoellner** [comment]
Looks like this feature is missing from the documentation.

**Comment by adrai** [comment]
@brettstack what is the current suggested way to call the proxy function? like in the readme (no callback, only context)? or with callback and how?

**Comment by brettstack** [comment]
Open to PRs updating the docs. I haven't performed a performance benchmark on context.succeed vs Promise resolution which is the main reason I didn't change the example

**Comment by zoellner** [comment]
Added a PR for the docs: #212

**Pull request merged**
