### PR TITLE
Accepting multiple values query parameters

### PR DESCRIPTION
**Pull request by albertossilva**
Please ensure all pull requests are made against the `develop` branch.

*Description of changes:* When multiple values parameters on query string are sent to an api gateway then to a lambda, the event have the attribute `multiValueQueryStringParameters`.

Example:
QueryString: `test?foo=one&foo=two`, will generate the event:
```
const event = {
    path: '/foo/bar',
    queryStringParameters: {
      'foo': 'two'
    },
    multiValueQueryStringParameters: {
      'foo': ['one', 'two']
    }
  }
```

The proxy generates just send `?foo=two` to express, with my fix it send the correct query String `?foo=one&foo=two`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by albertossilva** [comment]
The PR https://github.com/awslabs/aws-serverless-express/pull/215 remove the queryString as you can see in the file https://github.com/awslabs/aws-serverless-express/pull/215/files#diff-1fdf421c05c1140f6d71444ea2b27638. It should be merged as my fix does.

**Comment by brettstack** [comment]
@albertossilva should we close this in favor of #215? My understanding is that `multiValueQueryStringParameters` can be used in place of `queryStringParameters` instead of grabbing values from both.

**Comment by albertossilva** [comment]
If you just grab values just from multipleValue, would it lose the values on `queryStringParameters`? That is why I have merged both prioritizing the multipleValues.

if I am wrong please decline my one in favor of the previous one.

**Comment by albertossilva** [comment]
@brettstack If the query string is `foo=1&bar=2&bar=3` will the `foo` go to `multipleValueQueryStringParameters`?

**Comment by brettstack** [comment]
Yes, that's my understanding

**Comment by albertossilva** [comment]
@brettstack according to this link https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-api-as-simple-proxy-for-lambda.html on the example, the `mutipleValueQueryStringParameters` is sent containing arrays of one value, so when the querystring.format parse it will generate a correct query to express I hope. 

Unfortunately I can't test on Amazon till Thursday. 😥

**Comment by orenherman** [comment]
Any update on this? I've just encountered the same issue.

**Pull request closed without merging**
