### PR TITLE
Fix #20

### LINKED ISSUE #20: [Feature] Use params in config
Improve config to allow params instead of relying on order or args.

See #6 for more info.

### PR DESCRIPTION
**Pull request by jeremylevy**

### CODE REVIEW

**Comment by brettstack** [comment]
Thanks for the contribution. Please confirm this contribution is under the terms of the Apache 2.0 license.

Thanks.

**Comment by jeremylevy** [comment]
I confirm this contribution is under the terms of the Apache 2.0 license.

**Comment by jeremylevy** [comment]
It seems that this pull request was reverted. Let me know if I need to fix something.

**Comment by brettstack** [comment]
I prematurely merged this. I will get it in this week.

**Comment by brettstack** [comment]
This has been merged. Thanks for your contribution.

**Pull request merged**
