### PR TITLE
Support ALB + Lambda integration

### PR DESCRIPTION
**Pull request by TylorShin**
*Issue #, if available:*
comment of #152 

*Description of changes:*
With this branch's change, it's possible to handle the requests from ALB.

### CODE REVIEW

**Comment by massa-man** [comment]
@brettstack Is there any plan to release support for ALB + lambda soon? I am looking to deploy an isomorphic react JS application on lambda and would rather execute from ALB and not from API gateway, which provides better features and support for routing, redirection, etc.

This feature would be an incredible improvement to the project.

**Comment by TylorShin** [comment]
@massa-man I made it exactly same thing what u want to do and works nicely. I hope the integration will be made soon.

**Comment by alex-roman** [comment]
@brettstack can you please review/merge this?

**Comment by brettstack** [comment]
I'm currently adding support for this in v4. Anyone who needs this immediately can use this branch. @TylorShin thanks for the PR; I'll tag you in the commit (you can see current wip on v4 branch)

**Pull request closed without merging**
