### PR TITLE
Add options to aws-serverless-express module to strip base path

### PR DESCRIPTION
**Pull request by jamchen**
According to the discussion #86 and @m5m1th's observation, this PR provides an option for client to decide to strip base path or not. When user enables, stripBasePath, it will lookup the proxy path from event object, event.pathParameters.proxy.

### CODE REVIEW

**Comment by sbrickner** [comment]
@jamchen Do you have an estimated date when this fix might be released?

**Comment by jamchen** [comment]
@sbrickner I'm sorry that I'm not a member of the official project. I just encountered the problem and try to workaround it according to the discussion. Hopefully, they can offer a official solution soon.

**Comment by brettstack** [comment]
This is a breaking change. I'll see if I can implement this without introducing a breaking change.

**Comment by Mohan1996** [comment]
Hello. Is there any update on this issue, or workarounds? Currently stuck on it

**Comment by abbottdev** [comment]
Bump 😄

**Comment by brettstack** [comment]
Closing in favor of v4

**Pull request closed without merging**
